[package]
name = "mathoku-core"
version = "0.1.0"
edition = "2024"

[lib]
# cdylib enables .so output for the Kotlin wrapper
crate-type = ["cdylib"]
name = "mathoku"

[dependencies]
jni = "0.21.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
typeshare = "1.0.4"
